### ISSUE TITLE
The logs from the events service instance of the server

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/distributed_minispace#143]
The logs from the events service instance of the server

````
00:01 INF] Request starting HTTP/1.1 GET http://events-service:80/ping - null null
[20:00:01 INF] Request finished HTTP/1.1 GET http://events-service:80/ping - 200 null text/plain 0.1518ms
[20:00:02 INF] Request starting HTTP/1.1 POST http://api-gateway/events/search - application/json null
[20:00:02 INF] Executing endpoint 'HTTP: POST events/search'
[20:00:03 INF] Executed endpoint 'HTTP: POST events/search'
[20:00:03 INF] Request finished HTTP/1.1 POST http://api-gateway/events/search - 200 null application/json 1237.1754ms
[20:00:04 INF] Request starting HTTP/1.1 GET http://events-service:80/ping - null null
[20:00:04 INF] Request finished HTTP/1.1 GET http://events-service:80/ping - 200 null text/plain 0.1059ms
[20:00:05 INF] Request starting HTTP/1.1 GET http://api-gateway/events/24abc04e-855b-4af5-8715-e9f0a7391e27 - null null
[20:00:05 INF] Executing endpoint 'HTTP: GET events/{eventId}'
[20:00:05 INF] Executed endpoint 'HTTP: GET events/{eventId}'
[20:00:05 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MiniSpace.Services.Events.Infrastructure.Services.Clients.FriendsServiceClient..ctor(IHttpClient httpClient, HttpClientOptions options) in /app/src/MiniSpace.Services.Events.Infrastructure/Services/Clients/FriendsServiceClient.cs:line 18
   at InvokeStub_FriendsServiceClient..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Convey.CQRS.Queries.Dispatchers.QueryDispatcher.QueryAsync[TQuery,TResult](TQuery query, CancellationToken cancellationToken)
   at Convey.WebApi.CQRS.Builders.DispatcherEndpointsBuilder.<>c__DisplayClass3_0`2.<<Get>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Convey.WebApi.EndpointsBuilder.BuildQueryContext[T](HttpContext httpContext, Func`3 context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ApdexMiddleware.MeasureTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.PerRequestTimerMiddleware.TimeTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.RequestTimerMiddleware.TimeTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ErrorRequestMeterMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ActiveRequestCounterEndpointMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Convey.WebApi.Exceptions.ErrorHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[20:00:05 INF] Request finished HTTP/1.1 GET http://api-gateway/events/24abc04e-855b-4af5-8715-e9f0a7391e27 - 400 null application/json 4.3011ms
[20:00:07 INF] Request starting HTTP/1.1 GET http://events-service:80/ping - null null
[20:00:07 INF] Request finished HTTP/1.1 GET http://events-service:80/ping - 200 null text/plain 0.1691ms


```

**Comment by SaintAngeLs** [comment]
The bug we discussed in FB:


```
20:56:48 INF] Executing endpoint 'HTTP: POST events/search'
[20:56:48 INF] Executed endpoint 'HTTP: POST events/search'
[20:56:48 INF] Request finished HTTP/1.1 POST http://api-gateway/events/search - 200 null application/json 87.7098ms
[20:56:50 INF] Request starting HTTP/1.1 GET http://api-gateway/events/student/4faa1718-2902-4c9b-999a-7e3e557f1ee0?numberOfResults=10 - null null
[20:56:50 INF] Executing endpoint 'HTTP: GET events/student/{studentId}'
[20:56:50 INF] Start processing HTTP request GET http://localhost:5007/students/4faa1718-2902-4c9b-999a-7e3e557f1ee0/events
[20:56:50 INF] Sending HTTP request GET http://fabio:9999/localhost/students/4faa1718-2902-4c9b-999a-7e3e557f1ee0/events
[20:56:50 INF] Received HTTP response headers after 0.7572ms - 404
[20:56:50 INF] End processing HTTP request after 0.9968ms - 404
[20:56:50 INF] Executed endpoint 'HTTP: GET events/student/{studentId}'
[20:56:50 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MiniSpace.Services.Events.Infrastructure.Mongo.Queries.Handlers.GetStudentEventsHandler.HandleAsync(GetStudentEvents query, CancellationToken cancellationToken) in /app/src/MiniSpace.Services.Events.Infrastructure/Mongo/Queries/Handlers/GetStudentEventsHandler.cs:line 44
   at Convey.CQRS.Queries.Dispatchers.QueryDispatcher.QueryAsync[TQuery,TResult](TQuery query, CancellationToken cancellationToken)
   at Convey.WebApi.CQRS.Builders.DispatcherEndpointsBuilder.<>c__DisplayClass3_0`2.<<Get>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Convey.WebApi.EndpointsBuilder.BuildQueryContext[T](HttpContext httpContext, Func`3 context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ApdexMiddleware.MeasureTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.PerRequestTimerMiddleware.TimeTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.RequestTimerMiddleware.TimeTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ErrorRequestMeterMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ActiveRequestCounterEndpointMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Convey.WebApi.Exceptions.ErrorHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[20:56:50 INF] Request finished HTTP/1.1 GET http://api-gateway/events/student/4faa1718-2902-4c9b-999a-7e3e557f1ee0?numberOfResults=10 - 400 null application/json 4.7431ms
[20:56:51 INF] Request starting HTTP/1.1 GET http://events-service:80/ping - null null
[20:56:51 INF] Request finished HTTP/1.1 GET http://events-service:80/ping - 200 null text/plain 0.1401ms
(judgesite) root@debian-s-2vcpu-4gb-nyc1-01:~/webapps# 

````

**Comment by SaintAngeLs** [comment]
````
 processing HTTP request after 115.9873ms - 200
info: System.Net.Http.HttpClient.IHttpClient.LogicalHandler[100]
      Start processing HTTP request POST http://localhost:5000/events/24abc04e-855b-4af5-8715-e9f0a7391e27/sign-up
info: System.Net.Http.HttpClient.IHttpClient.ClientHandler[100]
      Sending HTTP request POST http://localhost:5000/events/24abc04e-855b-4af5-8715-e9f0a7391e27/sign-up
info: System.Net.Http.HttpClient.IHttpClient.ClientHandler[101]
      Received HTTP response headers after 84.2261ms - 400
info: System.Net.Http.HttpClient.IHttpClient.LogicalHandler[101]
      End processing HTTP request after 84.3157ms - 400
fail: MiniSpace.Web.HttpClients.IHttpClient[0]
      Error response from server: {"code":"student_not_found","reason":"Student with ID: \u0027af9ca0fc-b35b-4566-84e5-83dd08f20c3e\u0027 was not found."}
fail: MiniSpace.Web.HttpClients.IHttpClient[0]
      Received an invalid response to HTTP request from URI: http://localhost:5000/events/24abc04e-855b-4af5-8715-e9f0a7391e27/sign-up
      StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        Date: Sun, 12 May 2024 21:07:59 GMT
        Server: Kestrel
        Transfer-Encoding: chunked
        Request-Id: f9d4019176e5422ca41bdbf1b622d495
        Trace-ID: 0HN3IOQM8Q8SJ:0000000A
      }



````

**Comment by SaintAngeLs** [comment]
```
o: System.Net.Http.HttpClient.IHttpClient.ClientHandler[100]
      Sending HTTP request GET http://api-gateway/students
info: System.Net.Http.HttpClient.IHttpClient.ClientHandler[101]
      Received HTTP response headers after 5287.7253ms - 200
info: System.Net.Http.HttpClient.IHttpClient.LogicalHandler[101]
      End processing HTTP request after 5287.9021ms - 200
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[MiniSpace.Web.DTO.StudentDto]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
      To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
      Path 'results', line 1, position 11.
      Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[MiniSpace.Web.DTO.StudentDto]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
      To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
      Path 'results', line 1, position 11.
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at MiniSpace.Web.HttpClients.CustomHttpClient.GetAsync[T](String uri)
         at MiniSpace.Web.Pages.Admin.ManageStudents.OnInitializedAsync() in /app/src/MiniSpace.Web/Pages/Admin/ManageStudents.razor:line 73
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'VMdT3hr8OfNfmvH9upHQXUkEn1_AibikgY-nDfS5C_A'.
      Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[MiniSpace.Web.DTO.StudentDto]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
      To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
      Path 'results', line 1, position 11.
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
         at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
         at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
         at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
         at MiniSpace.Web.HttpClients.CustomHttpClient.GetAsync[T](String uri)
         at MiniSpace.Web.Pages.Admin.ManageStudents.OnInitializedAsync() in /app/src/MiniSpace.Web/Pages/Admin/ManageStudents.razor:line 73
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
root@debian-s-2vcpu-4gb-nyc1-01:~# 

```

**Comment by SaintAngeLs** [comment]
This issue will become closed due to inactivity.

**Comment by SaintAngeLs** [comment]
```
plication/json 10.9063ms
[18:39:15 INF] Request starting HTTP/1.1 POST http://api-gateway/events/search - application/json null
[18:39:15 INF] Executing endpoint 'HTTP: POST events/search'
[18:39:15 INF] Executed endpoint 'HTTP: POST events/search'
[18:39:15 INF] Request finished HTTP/1.1 POST http://api-gateway/events/search - 200 null application/json 90.9045ms
[18:39:17 INF] Request starting HTTP/1.1 GET http://api-gateway/events/student/4ee4d85f-4d77-4f3b-98c6-0a5c884289a7?engagementType=SignedUp&page=1&numberOfResults=5 - null null
[18:39:17 INF] Executing endpoint 'HTTP: GET events/student/{studentId}'
[18:39:17 INF] Start processing HTTP request GET http://students-service/students/4ee4d85f-4d77-4f3b-98c6-0a5c884289a7/events
[18:39:17 INF] Sending HTTP request GET http://fabio:9999/students-service/students/4ee4d85f-4d77-4f3b-98c6-0a5c884289a7/events
[18:39:17 INF] Received HTTP response headers after 2.7951ms - 404
[18:39:17 INF] End processing HTTP request after 3.4491ms - 404
[18:39:17 INF] Executed endpoint 'HTTP: GET events/student/{studentId}'
[18:39:17 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MiniSpace.Services.Events.Infrastructure.Mongo.Queries.Handlers.GetStudentEventsHandler.HandleAsync(GetStudentEvents query, CancellationToken cancellationToken) in /app/src/MiniSpace.Services.Events.Infrastructure/Mongo/Queries/Handlers/GetStudentEventsHandler.cs:line 50
   at Convey.CQRS.Queries.Dispatchers.QueryDispatcher.QueryAsync[TQuery,TResult](TQuery query, CancellationToken cancellationToken)
   at Convey.WebApi.CQRS.Builders.DispatcherEndpointsBuilder.<>c__DisplayClass3_0`2.<<Get>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Convey.WebApi.EndpointsBuilder.BuildQueryContext[T](HttpContext httpContext, Func`3 context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ApdexMiddleware.MeasureTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.PerRequestTimerMiddleware.TimeTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.RequestTimerMiddleware.TimeTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ErrorRequestMeterMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ActiveRequestCounterEndpointMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Convey.WebApi.Exceptions.ErrorHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[18:39:17 INF] Request finished HTTP/1.1 GET http://api-gateway/events/student/4ee4d85f-4d77-4f3b-98c6-0a5c884289a7?engagementType=SignedUp&page=1&numberOfResults=5 - 400 null application/json 11.9753ms
[19:21:54 INF] Request starting HTTP/1.1 POST http://api-gateway/events/search/organizer - application/json null
[19:21:54 INF] Executing endpoint 'HTTP: POST events/search/organizer'
[19:21:55 INF] Executed endpoint 'HTTP: POST events/search/organizer'
[19:21:55 INF] Request finished HTTP/1.1 POST http://api-gateway/events/search/organizer - 200 null application/json 1078.6622ms
[19:22:14 INF] Request starting HTTP/1.1 POST http://api-gateway/events - application/json null
[19:22:14 INF] Executing endpoint 'HTTP: POST events'
[19:22:14 INF] Start processing HTTP request GET http://organizations-service/organizations/b541bce8-5f7c-4d0a-8b66-f9fb2ba576f5/details?rootId=b541bce8-5f7c-4d0a-8b66-f9fb2ba576f5
[19:22:14 INF] Sending HTTP request GET http://fabio:9999/organizations-service/organizations/b541bce8-5f7c-4d0a-8b66-f9fb2ba576f5/details?rootId=b541bce8-5f7c-4d0a-8b66-f9fb2ba576f5
[19:22:14 INF] Received HTTP response headers after 2.1932ms - 404
[19:22:14 INF] End processing HTTP request after 2.7121ms - 404
[19:22:14 INF] Executed endpoint 'HTTP: POST events'
[19:22:14 ERR] Organization with id: 'b541bce8-5f7c-4d0a-8b66-f9fb2ba576f5' was not found.
MiniSpace.Services.Events.Application.Exceptions.OrganizationNotFoundException: Organization with id: 'b541bce8-5f7c-4d0a-8b66-f9fb2ba576f5' was not found.
   at MiniSpace.Services.Events.Application.Commands.Handlers.CreateEventHandler.HandleAsync(CreateEvent command, CancellationToken cancellationToken) in /app/src/MiniSpace.Services.Events.Application/Commands/Handlers/CreateEventHandler.cs:line 76
   at Convey.Logging.CQRS.Decorators.CommandHandlerLoggingDecorator`1.HandleAsync(TCommand command, CancellationToken cancellationToken)
   at Convey.CQRS.Commands.Dispatchers.CommandDispatcher.SendAsync[T](T command, CancellationToken cancellationToken)
   at Convey.WebApi.CQRS.Builders.DispatcherEndpointsBuilder.BuildCommandContext[T](T command, HttpContext context, Func`3 beforeDispatch, Func`3 afterDispatch)
   at Convey.WebApi.EndpointsBuilder.BuildRequestContext[T](HttpContext httpContext, Func`3 context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ApdexMiddleware.MeasureTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.PerRequestTimerMiddleware.TimeTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.RequestTimerMiddleware.TimeTransaction(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ErrorRequestMeterMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ActiveRequestCounterEndpointMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Convey.WebApi.Exceptions.ErrorHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[19:22:14 INF] Request finished HTTP/1.1 POST http://api-gateway/events - 400 null application/json 90.1828ms

```
